### ISSUE TITLE
Minor typo in installer

### ISSUE THREAD

**Issue by createchange** [deajan/smartmontools-win#25]
Just a heads up - in the installer, on the "select components" screen there is a typo. 

"Context menu for **drvies**" rather than "_drives_"

Thanks for this tool. 👍

**Comment by deajan** [comment]
Thanks :) I'll have this corrected.

**Comment by thoral** [comment]
Hi dajan, 

in v6.6.1 the single quotes problem still exists. Single quotes won't work invoking the erroaction batch.  

Also, there should be a hint that it is necessary to use the whole path (instead of just "erroraction.cmd".

BTW I tested my configuration with the help of a fake S.M.A.R.T. attribute ID for creating an alarm, like -C 12 (Power-Cycle-Count), which triggers an alarm immediately because of the high value. Invoking the daemon manually like smartd -d -c <path_to_config> is proving that the mail is being sent and that the pop up window work. 

What I did not understand was the return value of the script to smartd: exit status 1. I tried to find the reason but I had no success. (Everything seemed to work ...) Do you have an idea?

Thorsten

**Comment by deajan** [comment]
Closing this very old issue since it should be resolved.
